name: Flight Tracker

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run flight price tracker
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ORIGIN: "ORD"
          DESTINATION: "DEL"
          DEPART_DATE: "2026-12-11"
          PRICE_THRESHOLD: "450"
        run: python tracker.py